Построение G-AST дерева для сервиса
surfstudio/SurfGen pull request #1
Opened 2020-10-26 07:25 UTC by dmitryd20

2020-11-08 12:09 UTC, LastSprint commented on Sources/YamlParser/GASTBuilder/GASTBuilder.swift
> +        let builder = GASTDeclNodeBuilder()
Так делать не хорошо, т.к. у тебя получается неявная зависимость. Лучше объявить ее как явную зависимость и инжетить снаружи. То есть передавать в экземпляр GASTBuilder-а снаружи. 

Та же история с `GASTContentNodeBuilder` внутри `GASTDeclNodeBuilder`. 
Если так не сделать, то зависимости будут неявными и тестировать поведение будет невозможно, т.к. ты не можешь и замокать

2020-11-08 12:11 UTC, LastSprint commented on Sources/YamlParser/GASTBuilder/GASTContentNodeBuilder.swift
> +    func buildServiceContentSubnodes(with operations: [Operation]) throws -> ASTNode {
А не кажется, что лучше было бы все таки сделать отдельный класс? Кажется,  что мешать все в кучу не очень хорошая мысль, особенно учитывая, что в иерархии метод стоит выше модели

2020-11-08 12:36 UTC, LastSprint commented on Sources/YamlParser/GASTBuilder/GASTBuilderError.swift
> +            return "Cannot resolve content body of type \(type)"
Мало информации, добавь туда что-то еще, например имя метода. 
Обычно это делается так, что у тебя методы оборачивают ошибки. Например:
```swift

func methodB() throws { ... }

func methodA() throws {
    try methodB()
}
```

Сейчас сделано так. Тогда при получении ошибки ты будешь иметь только контакт метода B, но не метода A.  А если сделать вот так:
```swift
struct SurfGenError: Error, LocalizedError {
    var nested: Error?
    var message: String

    var errorDescription: String? {
        guard let err = self.nested else {
            return self.message
        }

        return "\(self.message)\n\t\(err.localizedDescription)"
    }
}


func methodB() throws -> Int {
    throw SurfGenError(nested: nil, message: "Method `B` message")
}

func methodA() throws -> Int {
    return try wrap(with: "Method `A` message", wraped: methodB())
}

func wrap<T>(with msg: String, wraped: @autoclosure () throws -> T) throws -> T {
    do {
        return try wraped()
    } catch {
        throw SurfGenError(nested: error, message: msg)
    }
}


do {
    try methodA()
} catch {
    print(error.localizedDescription)
}
```

И тогда будет выведено:
```txt
Method `A` message
	Method `B` message
```

2020-11-08 12:49 UTC, LastSprint commented on Tests/YamlParserTests/GASTBuilderTests/GASTMediaContentNodeBuilderTests.swift
> +    func testRequestBodyContent() {
Имя теста ничего не говорит о том, что ты им проверяешь. Хорошо использовать комбинацию:
- Ясное имя теста
- Ясный комментарий

Например так:
<img width="1119" alt="Снимок экрана 2020-11-08 в 15 42 49" src="https://user-images.githubusercontent.com/22478978/98465370-b5675500-21d9-11eb-9b38-615f4c017f52.png">

То есть сначала ты продумываешь тест-кейсы: "Что я буду здесь тестировать" или "Что может пойти не так" и то что в голове появляется выгружаешь в виде списка. И затем каждый элемент этого списка начинаешь тестировать. 

Плюс у тебя немного хаотично выполняются проверки, лучше делать это с подходом `AAA` - `Arrange Act Assert` потому что такой подход не даст мусорить в тестах и проверять по могу раз одно и то же, либо проверять слишком много всего в одном тесте

2020-11-08 12:54 UTC, LastSprint commented on Tests/YamlParserTests/GASTBuilderTests/GASTMediaContentNodeBuilderTests.swift
> +        do {
не обязательно заворачивать все в do-catch, можно пометить test-метод как throws

2020-11-08 13:01 UTC, LastSprint requested changes
Вроде бы все ок, нужно внести правки по тому что я отписал. 
И еще я вроде бы не увидел e2e тестов, где строилось бы дерево по всей спеке, а потом оно бы сравнивалось с ожидаемым деревом

2020-11-16 20:07 UTC, dmitryd20 commented on Sources/YamlParser/GASTBuilder/GASTBuilder.swift
> +        let builder = GASTDeclNodeBuilder()
Мне кажется, в таком случае было бы логично покрыть каждый узел протоколом и инжектить уже по протоколу. Есть ли в этом смысл?

2020-11-17 05:48 UTC, LastSprint commented on Sources/YamlParser/GASTBuilder/GASTBuilder.swift
> +        let builder = GASTDeclNodeBuilder()
Может быть сейчас нет. Но ты когда зависимости декларируешь в одном месте и передаешь через конструктор ты облегчаешь дальнейший процесс работы с кодом. Ну типа "ве-первых это проще читать", потому что у тебя явно прописаны зависимости этого класса. Ну и со всеми вытекающими - проще менять, проще поддерживать. 

Ну и у тебя уходят какие-то странные не нужные аллокации/деаллокации

2020-11-17 09:54 UTC, dmitryd20 commented on Sources/YamlParser/GASTBuilder/GASTContentNodeBuilder.swift
> +    func buildServiceContentSubnodes(with operations: [Operation]) throws -> ASTNode {
С точки зрения нашего генератора модель находится на одном уровне с сервисом, это структурная единица генерации. Соответственно роль `ContentNodeBuilder` - заполнение содержимого для этой единицы.
И если мы делаем явную зависимость, то в случае разделения для сервиса и модели уже здесь будут разные зависимости и появится вопрос, что нужно инициализировать, а что - нет.

2020-11-19 04:22 UTC, LastSprint commented on Sources/YamlParser/GASTBuilder/GASTContentNodeBuilder.swift
> +    func buildServiceContentSubnodes(with operations: [Operation]) throws -> ASTNode {
Не, моя мысль была в том что генератор для модели и для сервиса это должны быть разные генераторы вообще

2020-11-20 04:23 UTC, LastSprint commented on Sources/YamlParser/GASTBuilder/GASTContentNodeBuilder.swift
> +    func buildServiceContentSubnodes(with operations: [Operation]) throws -> ASTNode {
Впрочем эт не критично

2020-11-20 04:23 UTC, merged